version: '3'

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/home/developer/app
    command: "tail -F anything"
  
  db:
    env_file:
      - .env
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"

  minio:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.minio
    ports:
      - 9000:9000
      - 9001:9001      
    volumes:
      - minio_data:/data/
    #command: "tail -F anything"
    command: "minio server /data/"

  # minio:
  #   image: quay.io/minio/minio
  #   env_file:
  #     - .env
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: "minio server /data"

volumes:
  minio_data: